### ISSUE TITLE
Unable to use Ruto for dropdown fields

### ISSUE THREAD

**Issue by mkelemana91** [rutoXpath/Ruto#1]
**Environment:**

- Mac PC, MacOS Mojave, version 10.14.3
- Chrome Version 73.0.3683.75 (Official Build) (64-bit)

**Steps to reproduce**

- I added Ruto extension to my chrome browser and opened the website https://www.takealot.com. 

- I then tried to add the "All Departments" dropdown field (next to Search bar) to Ruto by right-clicking (Ctrl + click on Trackpad) on the field.  

**Limitation**
If you are unable to right-click on a field then you will also be unable to add that field (in this case a dropdown field) to Ruto. 

**Suggestion**
Allow a user to select an element to add on Ruto without right-clicking on the element. 
For example: 
Open Ruto > Click 'Select element to add to Ruto' > Go back to element you want to add > Click on that element ----> Element is added to Ruto!

Awesome tool by the way! Keep up the good work.

**Comment by ortoni** [comment]
Thanks for the suggestion, however if right click doesn't work still you can handle that by clicking on the ruto extension icon - right click on add to ruto.
( Refer the YouTube video) Regarding the issue we have fixed it and the extension will be updated with lot more new features. 

Thank you.
Ruto team
