### ISSUE TITLE
Its not working on Mac os 10.13.6

### ISSUE THREAD

**Issue by saravanan0209** [rutoXpath/Ruto#2]
After inspecting the element when i give add to ruto its not reflecting on the add on present in the browser .
Chrome version which i checked is 74 on  Mac os .
Its not supporting on Mac Os .
Please check over it.

**Comment by ortoni** [comment]
After installing ruto did you restart your browser ? 
Additional info like url to access or dom snap will be helpful.

**Comment by rutoXpath** [comment]
We have checked form our side and its working fine, Please do try again and let us know, also additional information like **url** of the application or snap of a **DOM** will help us to debug.
**Closing** this issue now.

**Comment by saravanan0209** [comment]
Its working after restarting. Thanks
